"""Init

Revision ID: 87604f3fa6ce
Revises: 242ceaaade46
Create Date: 2023-04-25 08:38:06.226164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87604f3fa6ce'
down_revision = '242ceaaade46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.alter_column('contacts', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
